menu:
  首页: /
  归档: /archives
  GitHub: https://github.com/inetfuture

widgets:
- search
- tag
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  weibo: true
  linkedin: true
  google: false
  facebook: true
  twitter: true

copyright:
  enable: true
  claim: 版权声明：自由转载-非商用-无演绎-保持署名 @ Creative Commons BY-NC-ND 3.0
  show_link: true

fancybox: true

google_analytics: UA-45019001-1
analytics_site_name: topdna.org
rss:
